### ISSUE TITLE
ReferenceError: modules is not defined

### ISSUE THREAD

**Issue by arminacck** [SegFaultx64/express-http-to-https#1]
I copy/pasted the exact example in the README.md file and ran it and it threw this error:

```
/path/to/my/app/node_modules/express-http-to-https/index.js:1
(function (exports, require, module, __filename, __dirname) { modules.exports = function redirectToHTTPS (ignoreHosts, ignoreRoutes) {
                                                              ^

ReferenceError: modules is not defined
    at Object.<anonymous> (/path/to/my/app/node_modules/express-http-to-https/index.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/my/app/server/test.js:4:23)
    at Module._compile (module.js:570:32)
```

What's the issue?

**Comment by mitchellirvin** [comment]
+1

**Comment by mitchellirvin** [comment]
If manually changing 'modules' to 'module' does not work for you (didn't for me because I needed to pull this for a prod app) then try using https://www.npmjs.com/package/express-https-redirect

**Comment by SegFaultx64** [comment]
Hi @mitchellirvin and @github-armin, sorry for letting this sit for so long. It should be resolved now.
