### ISSUE TITLE
TypeError: search.test is not a function

### ISSUE THREAD

**Issue by joncorrin** [SegFaultx64/express-http-to-https#5]
I'm using an angular4/nodejs app. 

In production, it seems to work fine, but with localhost I'm getting the type error in the title. 

here is my stack trace
```
TypeError: search.test is not a function
    at ignores.some (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express-http-to-https/index.js:3:19)
    at Array.some (native)
    at searchIgnore (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express-http-to-https/index.js:2:18)
    at middlewareRedirectToHTTPS (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express-http-to-https/index.js:12:25)
    at Layer.handle [as handle_request] (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/application.js:174:10)
    at Server.app (/Users/jonathancorrin/Desktop/workspace/rent-app/node_modules/express/lib/express.js:38:9)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)


```

Here is my node code
```
const redirectToHTTPS = require("express-http-to-https").redirectToHTTPS;

const app = express();

require('dotenv').config();

app.set('views', path.join(__dirname, './dist'));
app.set('view engine', 'ejs');

app.use(redirectToHTTPS([[/localhost:(\d{4})/]]));
```

Also, on a side note I ran it through chrome's lighthouse pwa tool and it states Im still not redirecting http tp https??

**Comment by SegFaultx64** [comment]
Hi @joncorrin 

Sorry for the delay on responding to this (I was out of the country).

The issue here appears to be and extra set of `[]` in your code here:

```js
app.use(redirectToHTTPS([[/localhost:(\d{4})/]]));
```

should be:

```js
app.use(redirectToHTTPS([/localhost:(\d{4})/]));
```

I am going to close this for now, assuming that was the issue (changing that made it work for me). If you still have trouble please feel free to reopen. 

As to the lighthouse pwa tool, can you open a new issue for that with a bit more detail if that is still a concern?

Best,

Max
